### ISSUE TITLE
I want to display the bbox of FN, what should I do

### ISSUE THREAD

**Issue by DaQiZi** [Cartucho/mAP#65]
I wanted to look at the results of FN, and I saw in the code that it was prompted to use the orange box to mark FN, but I didn't see the results when I run the code.
![image](https://user-images.githubusercontent.com/33093772/54594145-05c0fa80-4a6b-11e9-9075-2020de5451e2.png)
Just like this picture, the bbox of TP is shown.But the FN in the upper right corner is not shown. How can I modify the code? Thank you
![image](https://user-images.githubusercontent.com/33093772/54594320-5d5f6600-4a6b-11e9-9d4f-9e4a7632f536.png)

**Comment by Cartucho** [comment]
Hello! That is a great idea, I will add it to my TODO list.
I am currently restructuring the full code and the False Negatives are not being plotted yet.

I will add it as soon as possible!

**Comment by DaQiZi** [comment]
Thanks for your hard work

**Comment by bhaswara** [comment]
Hi @Cartucho , Have you solved this problem? Thanks

**Comment by denissato** [comment]
Hi @DaQiZi, You got it?

**Comment by Cartucho** [comment]
Hey guys! I have been with no time. I will try to do it now (:

**Comment by Cartucho** [comment]
I just added it! If you update it, it should now draw the false negatives in pink.

**Comment by denissato** [comment]
Man!!!! Thank tou Very much! I'm working in a object detection project to
use in roadways! My objective is detect animals! So show what objects
present in gt wasn't detected is more important! I was very happy with the
news!
I'm citting your work! Thank you very much!



Em qui, 12 de mar de 2020 20:15, Cartucho <notifications@github.com>
escreveu:

**Comment by denissato** [comment]
@Cartucho 
Now I'm facing the problem:

File "main.py", line 750, in <module>
    cv2.imwrite(img_cumulative_path, img)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/loadsave.cpp:715: error: (-215:Assertion failed) !_img.empty() in function 'imwrite'

First I thought that was some problem in jpg files. But I'm not understanding what happening!

**Comment by denissato** [comment]
@Cartucho Something is happening during draw FN bb. In my case, when some image has not any detection, the file doesn't have coordinates content. So that image is not saved in output. But is a false negative...so, the mAP is computing these situations? 
I believe that the algorithm is comparing detection bounding-boxes with ground-truth bounding boxes but if it isn't detection in an image, this file is not considered!
For example, I have a 024.jpg file that has a ground-truth 024.txt, but the object wasn't detected and the 024.txt detection-result file is empty. When I run the evaluation, receive the bellow error, cause I believe that the image was not generated:

Traceback (most recent call last):
  File "main.py", line 750, in <module>
    cv2.imwrite(img_cumulative_path, img)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgcodecs/src/loadsave.cpp:715: error: (-215:Assertion failed) !_img.empty() in function 'imwrite'

**Comment by Cartucho** [comment]
hey! I think someone just fixed that bug through a PR

**Comment by Cartucho** [comment]
@denissato could you please try the newest version? it should work now

**Comment by C-H-I-R-A-G** [comment]
@Cartucho here we got a false negative with the pink bounding box but at the output result, there are false-positive and true positive numbers, how to count false negative?
